### ISSUE TITLE
Nefukční test

### ISSUE THREAD

**Issue by erikdung** [JakubMrozek/eet#1]
Ahoj, díky za modul. Na tohle jsem čekal. Bohužel se mi to nedaří zprovoznit demo příklad.
Dostal jsem error:
(node:90107) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Neplatny podpis SOAP zpravy (4)
(node:90107) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JakubMrozek** [comment]
A tohle ti funguje?

``` javascript
const eet = require('eet')
const fs = require('fs')

// privatni klic a certifikat podnikatele
const options = {
  privateKey: fs.readFileSync('./node_modules/eet/test/keys/private.pem'),
  certificate: fs.readFileSync('./node_modules/eet/test/keys/certificate.pem'),
  playground: true
}

// polozky, ktere se posilaji do EET
const items = {
  dicPopl: 'CZ1212121218',
  idPokl: '/5546/RO24',
  poradCis: '0/6460/ZQ42',
  datTrzby: new Date(),
  celkTrzba: 34113,
  idProvoz: '273'
}

// ziskani FIK v Node.js 6+
eet(options, items).then(response => {
  // response.fik
  console.log(response)
})
```

Pokud ti tohle projde, tak je chyba v certifikátech. Zkontroluj, zda je privátní klíč i certifikát správný.

**Comment by JakubMrozek** [comment]
Jinak testováno na Node.js v6.8.1 a Macu.

**Comment by erikdung** [comment]
tak už jsem našel tu příčinu, u těch klíčů se vygenerují při převodu z .p12 ještě tyto věci
`Bag Attributes
    localKeyID: 79 A6 E8 CF 65 CF 6E D2 D7 B5 F3 B4 9F 53 9C F5 76 BE E0 F6 
Key Attributes: <No Attributes>`
Když jsem to smazal z těch klíčů, tak to funguje. Možná je dobré to napsat také do sekce, kde máš
ten návod na převod z .p12 na .pem :)
Díky za pomoc 👍

**Comment by JakubMrozek** [comment]
Aha, díky, doplním to tam při příštím releasu.

**Comment by JakubMrozek** [comment]
Upravena dokumentace.

**Comment by janoskaz** [comment]
Demo příklad mi nefunguje, nevypršela platnost klíče/cetifikátu?
