### ISSUE TITLE
Formát času...

### ISSUE THREAD

**Issue by pestasoft** [JakubMrozek/eet#12]
Ahoj, 
jestli dobře koukám na popis EET:

> Datum a čas odeslání datové zprávy se uvádí jako lokální čas v dané časové zóně s povinným vyznačením časové zóny podle následujícího pravidla:
> • +01:00 v případě, že hodnota spadá do období zimního času v ČR – tj. časová zóna je SEČ
> • +02:00 v případě, že hodnota spadá do období letního času v ČR – tj. časová zóna je SELČ
> • +hh:mm, nebo –hh:mm nebo Z v případě, že hodnota je uvedena v jiné časové zóně (mimo ČR).
 
Pro EET z ČR má být tedy lokální čas ve tvaru yyyy-mm-ddThh:mm:ss+0X:00 a ne UTC yyyy-mm-ddThh:mm:ssZ. Pokud jsem to pochopil správně je třeba poupravit funkci formatDate nějak takto:

```
function formatDate (date) {
    var pom=new Date(date);
    var tzo = (pom.getTimezoneOffset()/60)*(-1);
    pom.setHours(pom.getHours()+tzo);  
    return pom.toISOString().split('.')[0]+(tzo<0?'-':'+')+'0'+tzo+':00';
}
```

**Comment by JakubMrozek** [comment]
Ahoj, EET bere korektně i ten formát, který tam aktuálně máme. Tady je jejich schéma: http://www.etrzby.cz/assets/cs/prilohy/EETXMLSchema.xsd a datum a čas se tam uvádí takto:

```
<xs:simpleType name="dateTime">
  <xs:restriction base="xs:dateTime">
    <xs:pattern value="\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(Z|[+\-]\d\d:\d\d)"/>
  </xs:restriction>
</xs:simpleType>
```

Bere tedy správně obě formy. Dokumentace také zmiňuje, že je možné `Z` místo +01/+02 použít.
