### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by erikdung** [JakubMrozek/eet#14]
Ahoj,
chtěl jsem se zeptat na zkušenosti na Windowsech. Není tam defaultně nainstalovaný openssl. Zkoušel jsem to tam instalovat, ale nefunguje to. Nemáte někdo s tím zkušenosti? Díky

**Comment by omasopust** [comment]
@erikdung Já použil OpenSSL 1.0.2j 32bit nainstalovaný do C:/OpenSSL-Win32 a funguje.
