### ISSUE TITLE
Node 4.4.5 (METEOR) - Chyba při definici: let {pkp, bkp}

### ISSUE THREAD

**Issue by BenjaminMerlynS** [JakubMrozek/eet#15]
Ahoj ! Zaprví moc děkuji za modul, nevim co bych bez něho dělal...

Pracuji s frameworkem Meteor.js který běží na Node 4.4.5. Když spouštím funkci eet(options, items), tak se mi zastaví server a zobrazí se mi chyba při definici
 `let {pkp, bkp} = getFooterItems(options.privateKey, items)`

Chyba:
`SyntaxError: Unexpected token {`

_Jestli správně chápu tak Node/Meteor nedokažou přečíst definici proměné v tomto formátu_

Máte někdo nápad co spůsobuje tuto chybu? Čili jestli máte řešení?

Díky moc !

**Comment by JakubMrozek** [comment]
Problém je v tom, že Node.js 4.x neumí destruktury.

Existuji tři možnosti, jak to řešit:
a) upgrade na Node.js 6+
b) spouštět node.js s harmony přiznakem  jako `node --harmony_destructuring server.js`
c) forknout repo a upravit tuto část např. takto:

```js
let code = getFooterItems(options.privateKey, items)
let bkp = code.bkp
let pkp = code.pkp
```

**Comment by BenjaminMerlynS** [comment]
Děkuji za opdověď a rešení! 
Je to co jsem si myslel ! 

Bohužel nejde Node v Meteoru updatnout... To musejí oni s pokrokem verzi. Stejně tak neni možné zvlášť spouštět Node. Takže forknu repo !

Jestli je zájem tak rád udělám Pull Request se změnou pro kompatibilitu s Node v4 !

**Comment by mfeuermann** [comment]
Ahoj to by bylo fajn, urcite bych taky vyuzil...

**Comment by omasopust** [comment]
+1, taky bych to využil.

**Comment by omasopust** [comment]
@BenjaminMerlynS ahoj, jak to vypadá s PR? Bude, nebo se do toho mám pustit?

**Comment by BenjaminMerlynS** [comment]
@omasopust Omlouvám se za spoždění... Tento týden jsem nestíhal !

#16 Adaptace Node v4

**Comment by JakubMrozek** [comment]
Doplněno ve v0.7, díky.
