### ISSUE TITLE
Exposing generatePKP, generateBKP function

### ISSUE THREAD

**Issue by adasek** [JakubMrozek/eet#8]
Zdravím,
vytvářím na základě této knihovny klienta pro eet komunikujícího prostřednictvím příkazové řádky (pro existující pokladní systém v čajovně).
Moje rozhraní vůči existujícímu programu je jednoduché: 
return code 0 => tržba proběhla online, STDOUT= FIK
return code 1 => tržba proběhla offline, STDOUT=BKP, PKP
return code 2=> jiná chyba (špatné)
(pro ukládání offline tržeb používám sqlite a napíšu cronem invokovaný script který se bude snažit o znovuposlání)

V souvislosti s tím tedy potřebuji získat BKP a PKP, pokud požadavek neuspěje (testování - vytáhnutý síťový kabel :)), abych jej natiskl na účtenku. Oproti příkladu užití tak musím napsat něco jako:

```javascript
var eet = require('eet/lib/eet');
var util = require('eet/lib/util');
var pkp = eet.generatePKP(privateKey,dicPopl,idProvoz,idPokl,poradCis,util.formatDate(record.datTrzby),util.formatNumber(record.celkTrzba));
var bkp = eet.generateBKP(pkp);
```
předpokládám ale, že tím používám vnitřní části knihovny, které se mohou bez upozornění změnit.

Protože předpokládám, že jde o dost častý use-case (možnost realizovat offline transakce), chtělo by to takto doplnit rozhraní knihovny - nejintuitivnější mi přijde, vracet BKP a PKP jako součást rejectu v doRequest, co myslíte?

**Comment by JakubMrozek** [comment]
To se mi líbí, dobrý nápad, jsem pro. Co ostatní?

**Comment by koubas** [comment]
Ahoj, k tomuto mám ještě jeden tip: bylo by dobré oddělit tuto část jako samostatný modul a používat v něm crypto knihovnu, která funguje i v browserech, např.  jsrsasign.
Díky tomu bude možné generovat PKP/BKP na klientu i bez spojení na nodejs server, který zařizuje SOAP komunikaci (přepsat celou knihovnu, aby fungovala v browseru, by bylo samozřejmě ještě lepší, ale minimálně kvůli použité ws-security s certem to vypadá dost netriviálně).
Až to hotfixnu v mém aktuálním Cordova projektu, kde to vzhledem k aktuálnímu datu trochu spěchá, tak to sem možná contributnu.

**Comment by adasek** [comment]
@koubas To je sice technicky velmi zajimave, ale jet to v browseru znamena mit nad nim absolutni kontrolu = musis mu dat privatni klic a pokud si offline vygeneruje BKP a PKP a pak si treba vymaze cache, mas potencialni prusvih.
Jsi si jist ze je na to uziti?

**Comment by koubas** [comment]
V regulernim browseru moc ne, ale delam mobilni appku v Cordova, coz je zjednodusene fullscreen prohlizec, v kterem je pribalena webova aplikace a cele je to zabalene v APK (nebo obdobnem balicku jine platformy).
S jsrsasign uz jsem to uspesne rozbehal, lokalni data ukladam do WebSql, mozna to jeste zmenim na nativni Sqlite Cordova plugin, protoze na iOS (na kterem to ale zatim provozovano nebude) se i k WebSql datum chova jako k cache a udajne to obcas opravdu nahodne maze.

**Comment by mfeuermann** [comment]
Ja myslim ze Cordova je na tom velmi podobne jako klasicky browser... Ja bych do toho asi nesel...

**Comment by koubas** [comment]
@mfeuermann No jsme uz sice offtopic, ale co se ti na tom nezda? Potencialni problem s ulozistem (navic iOS specificky) ma reseni, ktere navic zvysuje portovatelnost na dalsi platformy, ktere nemaji WebSql, co dal? Do flame web vs. nativni appky se poustet nebudu, v mem usecasu to ma vpodstate jenom vyhody :)

**Comment by mfeuermann** [comment]
@koubas spis jsem navazoval na to co psal adasek ohledne absolutni kontroly nad prohlizecem. Prehlidnul jsem ale tvuj post s pouzitim toho sqlite pluginu..

**Comment by adyba** [comment]
@koubas @mfeuermann Ja bych se toho nebal. V podstate jde jenom o refactoring a je kazdeho riziko, jak  to naimplementuje. Kdyz uz to je v JS melo by se to dat spustit kdekoliv. Osobne bych se asi vyhnul Cordove a rovnou to naimportoval do Ionic2/Angular2 aplikace. Oba uz maji Ahead-of-time compilation, takze se to cely predzvejka jeste na dev desktopu a do hotove APK uz jde necitelny kod ergo riziko je podobne jako u nativniho kodu. Kdyz uz je kod programu necitelnej daji se klice osolit zleva zprava, popripade znova preliznout nejakou sifrou a pak by uz asi nemel byt problem je ulozit kamkoliv.
(ucite to jde i v Reactu ale o tom vim uplny NIC)

**Comment by pestasoft** [comment]
Nevyznám se v node.js až tak moc, ale nestačilo by takto pozměnit soubor eet.js okolo řádku 70? Místo chyby vrací objekt s chybou i oběma potřebnými kódy.

return new Promise((resolve, reject) => {
    const body = getBodyItems(options.privateKey, date, uid, items)
    soap.createClient(WSDL, soapOptions, (err, client) => {
      if (err) return reject(err)
      client.setSecurity(new WSSecurity(options.privateKey, options.certificate, uid))
      client.OdeslaniTrzby(body, (err, response) => {
        if (err) return reject(**{err:err, pkp:body.KontrolniKody.pkp.$value, bkp:body.KontrolniKody.bkp.$value}**)
        try {
          validate.httpResponse(response)
          resolve(getResponseItems(response))
        } catch (e) {
          reject(**{err:e, pkp:body.KontrolniKody.pkp.$value, bkp:body.KontrolniKody.bkp.$value}**)
        }
      }, {timeout: timeout})
    })
  })
